name: smart_tasks
description: "A modern Flutter task management application with AI-powered descriptions."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_modular: ^6.3.4
  fpdart: ^1.1.0
  intl: ^0.19.0
  sqflite: ^2.4.1
  path: ^1.8.3
  http: ^1.2.0
  tutorial_coach_mark: ^1.2.11
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  sqflite_common_ffi: ^2.3.2+1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
